const express=require("express"),path=require("path"),crypto=require("crypto"),bcrypt=require("bcryptjs"),fs=require("fs");
const {Pool}=require("pg"),session=require("express-session"),pgSession=require("connect-pg-simple")(session);
const app=express(),PORT=process.env.PORT||3000;
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
app.set("trust proxy",1);
app.use(express.json({limit:"1mb",verify:(req,res,buf)=>{if(req.originalUrl==="/api/payments/webhook")req.rawBody=buf}}));
app.use(session({store:new pgSession({pool,tableName:"user_sessions",createTableIfMissing:true}),secret:process.env.SESSION_SECRET||"change-me",resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:2592000000}}));
app.use(express.static(path.join(__dirname,"public")));
const q=(s,p=[])=>pool.query(s,p).then(r=>r.rows);
const auth=(req,res,next)=>req.session.user?next():res.status(401).json({error:"Please log in."});
const admin=(req,res,next)=>req.session.user?.role==="admin"?next():res.status(403).json({error:"Admin access required."});
const view=u=>({id:u.id,email:u.email,role:u.role,paid:u.paid,subscription_status:u.subscription_status});
async function initDatabase(){
  await q("CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',paid BOOLEAN NOT NULL DEFAULT FALSE,subscription_status TEXT NOT NULL DEFAULT 'inactive',paystack_customer_code TEXT,paystack_subscription_code TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())");
  await q("CREATE TABLE IF NOT EXISTS tracks (id SERIAL PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,title TEXT NOT NULL,prompt TEXT NOT NULL,genre TEXT NOT NULL,vibe TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'generating',provider_id TEXT,audio_url TEXT,duration INTEGER,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())");
  await q("CREATE TABLE IF NOT EXISTS payments (id SERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,reference TEXT UNIQUE NOT NULL,amount INTEGER NOT NULL,currency TEXT NOT NULL,status TEXT NOT NULL,raw JSONB,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())");
  await q("CREATE TABLE IF NOT EXISTS user_sessions (sid VARCHAR NOT NULL PRIMARY KEY,sess JSON NOT NULL,expire TIMESTAMP(6) NOT NULL)");
}
async function ensureAdmin(){if(!process.env.DATABASE_URL)return;const admins=[[process.env.ADMIN_EMAIL,process.env.ADMIN_PASSWORD],[process.env.ADMIN2_EMAIL,process.env.ADMIN2_PASSWORD]];for(const [email,password] of admins){if(!email||!password)continue;const h=await bcrypt.hash(password,12);await q("INSERT INTO users(email,password_hash,role,paid,subscription_status) VALUES($1,$2,'admin',TRUE,'admin') ON CONFLICT(email) DO UPDATE SET password_hash=EXCLUDED.password_hash,role='admin',paid=TRUE,subscription_status='admin'",[email.trim().toLowerCase(),h])}}
app.get("/health",async(_req,res)=>{try{await q("SELECT 1");res.json({ok:true,app:"BEATLYNXAI",version:"1.0.0"})}catch(e){res.status(503).json({ok:false})}});
app.post("/api/auth/register",async(req,res)=>{try{const email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||"");if(!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return res.status(400).json({error:"Use a valid email and a password of at least 8 characters."});if((await q("SELECT id FROM users WHERE email=$1",[email])).length)return res.status(409).json({error:"An account with that email already exists."});const h=await bcrypt.hash(password,12),u=(await q("INSERT INTO users(email,password_hash) VALUES($1,$2) RETURNING *",[email,h]))[0];req.session.user=view(u);req.session.save(err=>{if(err){console.error("Session save error during registration:",err);return res.status(500).json({error:"Unable to create session."})}res.json({user:req.session.user})})}catch(e){console.error("Registration error:",e);res.status(500).json({error:"Unable to create account."})}});
app.post("/api/auth/login",async(req,res)=>{try{const email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||""),u=(await q("SELECT * FROM users WHERE email=$1",[email]))[0];if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:"Invalid email or password."});req.session.user=view(u);req.session.save(err=>{if(err){console.error("Session save error during login:",err);return res.status(500).json({error:"Unable to create login session."})}res.json({user:req.session.user})})}catch(e){console.error("Login error:",e);res.status(500).json({error:"Unable to log in."})}});
app.post("/api/auth/logout",(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get("/api/auth/me",async(req,res)=>{if(!req.session.user)return res.json({user:null});const u=(await q("SELECT * FROM users WHERE id=$1",[req.session.user.id]))[0];if(!u)return res.json({user:null});req.session.user=view(u);res.json({user:req.session.user})});
async function generateAudio(prompt){if(!process.env.STABILITY_API_KEY)throw Error("AI music provider is not configured yet.");const fd=new FormData();fd.append("prompt",prompt);fd.append("output_format","mp3");fd.append("duration","30");fd.append("model","stable-audio-2.5");const r=await fetch("https://api.stability.ai/v2beta/audio/stable-audio-2/text-to-audio",{method:"POST",headers:{authorization:"Bearer "+process.env.STABILITY_API_KEY,accept:"audio/*"},body:fd});if(!r.ok)throw Error("Music provider rejected the generation request.");return Buffer.from(await r.arrayBuffer())}
app.post("/api/generate",auth,async(req,res)=>{let t;try{const prompt=String(req.body.prompt||"").trim(),genre=String(req.body.genre||"Pop"),vibe=String(req.body.vibe||"Energetic");if(!prompt)return res.status(400).json({error:"Describe the music you want to create."});t=(await q("INSERT INTO tracks(user_id,title,prompt,genre,vibe,status) VALUES($1,$2,$3,$4,$5,'generating') RETURNING *",[req.session.user.id,prompt.slice(0,60),prompt,genre,vibe]))[0];const audio=await generateAudio([genre,vibe,prompt].join(", "));fs.mkdirSync(path.join(__dirname,"storage"),{recursive:true});const file=t.id+"-"+crypto.randomBytes(8).toString("hex")+".mp3";fs.writeFileSync(path.join(__dirname,"storage",file),audio);const url="/api/tracks/"+t.id+"/audio";t=(await q("UPDATE tracks SET status='ready',audio_url=$1,duration=30 WHERE id=$2 RETURNING *",[url,t.id]))[0];res.json({track:t})}catch(e){if(t)await q("UPDATE tracks SET status='failed' WHERE id=$1",[t.id]);res.status(500).json({error:e.message||"Generation failed."})}});
app.get("/api/tracks",auth,async(req,res)=>{const rows=await q("SELECT id,title,prompt,genre,vibe,status,duration,created_at,audio_url FROM tracks WHERE user_id=$1 ORDER BY created_at DESC",[req.session.user.id]);res.json({tracks:rows.map(t=>({...t,downloadable:req.session.user.role==="admin"||req.session.user.paid}))})});
app.get("/api/tracks/:id/audio",auth,async(req,res)=>{const t=(await q("SELECT * FROM tracks WHERE id=$1",[req.params.id]))[0];if(!t||t.user_id!==req.session.user.id)return res.status(404).end();if(req.query.download==="1"&&req.session.user.role!=="admin"&&!req.session.user.paid)return res.status(402).json({error:"A paid subscription is required to download music."});const file=t.audio_url&&path.basename(t.audio_url),full=file&&path.join(__dirname,"storage",file);if(!full||!fs.existsSync(full))return res.status(404).json({error:"Audio file is not available."});res.type("audio/mpeg");if(req.query.download==="1")res.setHeader("Content-Disposition",`attachment; filename="${file}"`);fs.createReadStream(full).pipe(res)});
app.post("/api/payments/initialize",auth,async(req,res)=>{try{if(!process.env.PAYSTACK_SECRET_KEY||!process.env.PAYSTACK_PLAN_CODE)return res.status(503).json({error:"Payments are not configured yet."});const r=await fetch("https://api.paystack.co/transaction/initialize",{method:"POST",headers:{Authorization:"Bearer "+process.env.PAYSTACK_SECRET_KEY,"Content-Type":"application/json"},body:JSON.stringify({email:req.session.user.email,plan:process.env.PAYSTACK_PLAN_CODE,callback_url:(process.env.APP_URL||"")+"/?payment=complete"})}),d=await r.json();if(!r.ok||!d.status)return res.status(502).json({error:"Unable to start payment."});res.json({authorization_url:d.data.authorization_url,reference:d.data.reference})}catch(e){res.status(500).json({error:"Payment initialization failed."})}});
app.post("/api/payments/webhook",async(req,res)=>{const sig=crypto.createHmac("sha512",process.env.PAYSTACK_SECRET_KEY||"").update(req.rawBody||Buffer.from("")).digest("hex");if(sig!==req.headers["x-paystack-signature"])return res.status(401).end();const ev=req.body;if(ev.event==="charge.success"){const email=ev.data.customer?.email?.toLowerCase(),ref=ev.data.reference,u=(await q("SELECT id FROM users WHERE email=$1",[email]))[0];if(u){await q("UPDATE users SET paid=TRUE,subscription_status='active',paystack_customer_code=$1 WHERE id=$2",[ev.data.customer.customer_code,u.id]);await q("INSERT INTO payments(user_id,reference,amount,currency,status,raw) VALUES($1,$2,$3,$4,'success',$5) ON CONFLICT(reference) DO NOTHING",[u.id,ref,ev.data.amount,ev.data.currency,ev.data])}}if(["subscription.disable","subscription.not_renew"].includes(ev.event)){const email=ev.data.customer?.email?.toLowerCase();if(email)await q("UPDATE users SET paid=FALSE,subscription_status='inactive' WHERE email=$1",[email])}res.json({received:true})});
app.get("/api/admin/users",admin,async(_req,res)=>res.json({users:await q("SELECT id,email,role,paid,subscription_status,created_at FROM users ORDER BY created_at DESC")}));
app.get("/api/admin/tracks",admin,async(_req,res)=>res.json({tracks:await q("SELECT t.*,u.email FROM tracks t JOIN users u ON u.id=t.user_id ORDER BY t.created_at DESC")}));
app.get("*",(_req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
(async()=>{try{await initDatabase();await ensureAdmin();console.log("BEATLYNXAI database and admin initialization complete");}catch(e){console.error("Startup database initialization failed:",e)}})();
app.listen(PORT,"0.0.0.0",()=>console.log("BEATLYNXAI running on port "+PORT));